### PR TITLE
Fix frontend scripts logging errors

### PR DESCRIPTION
**Pull request by Karyum**
#129

### CODE REVIEW

**Comment by Karyum** [comment]
@finnhodgkin other than changing the title im not sure what needs to be done here?

**Comment by finnhodgkin** [comment]
Get rid of all the arrow functions, vars, etc.

Not high priority or particularly necessary but worth considering so the whole codebase is nice and consistent.

**Comment by Karyum** [comment]
@finnhodgkin Okay both of us were confused :laughing: this pull request is just to fix the problem for the front end scripts where i needed to add if statements to some scripts to it wouldnt send an erro on the browser, so this pull request **is not** refactoring the frontend code to es6

**Comment by Karyum** [comment]
i still have not yet raised an issue for refactoring front end #106

**Comment by finnhodgkin** [comment]
Yeah that makes sense, but don't you also make that change in #130 https://github.com/foundersandcoders/nazareth-events/pull/130/files#diff-b614c90f583df8807f962d02472fc00a

**Comment by finnhodgkin** [comment]
That's why I thought maybe it would make sense to use this PR for that instead.

**Pull request merged**
